### ISSUE TITLE
when I execute ufonode v1.0.1 with "--treasury=treasury.bin", it prompt that "unrecognised option '--treasury=treasury.bin'"

### ISSUE THREAD

**Issue by davidufochain** [ufo-project/ufochain#10]
when I execute ufonode v1.0.1 with "--treasury=treasury.bin", it prompt that "unrecognised option '--treasury=treasury.bin'"
below is command:
./ufo-node --treasury=treasury.bin --port=20001 --peer mainnet-node01.ufo.link:20015, mainnet-node02.ufo.link:20015, mainnet-node03.ufo.link:20015, 160.19.49.116:20015, 160.19.49.122:20015, 160.19.50.241:20015, 160.19.50.228:20015 --stratum_port=20002 --stratum_use_tls=0 --mining_threads=0 --miner_key=xxx --owner_key=xxx --pass=xxx
does i have some mistake? 
and --miner-key=xxx need write by the style --miner-key="xxx"?

_Originally posted by @davidufochain in https://github.com/ufo-project/ufochain/issues/9#issuecomment-604231868_

~/ufo/ufo-1.0.1-x86_64-linux-gnu# ./ufo-node --help
Allowed options:

General options:
-h [ --help ] list of all options
--log_level arg log level [info|debug|verbose]
--file_log_level arg file log level [info|debug|verbose]
--log_cleanup_days arg (=5) old logfiles cleanup period(days)
-v [ --version ] return project version
--git_commit_hash return commit hash

Node options:
-p [ --port ] arg (=10000) port to start the server on
--storage arg (=node.db) node storage path
--mining_threads arg (=0) number of mining threads(there is no
mining if 0)
--verification_threads arg (=-1) number of threads for cryptographic
verifications (0 = single thread, -1 =
auto)
--nonceprefix_digits arg (=0) number of hex digits for nonce prefix
for stratum client (0..6)
--peer arg nodes to connect to
--stratum_port arg (=0) port to start stratum server on
--stratum_secrets_path arg (=.) path to stratum server api keys file,
and tls certificate and private key
--stratum_use_tls arg (=1) enable TLS on startum server
--reset_id arg (=0) Reset self ID (used for network
authentication). Must do if the node is
cloned
--erase_id arg (=0) Reset self ID (used for network
authentication) and stop before
re-creating the new one.
--check_db arg (=0) DB integrity check and compact (vacuum)
--bbs_enable arg (=1) Enable SBBS messaging
--crash arg (=0) Induce crash (test proper handling)
--owner_key arg Owner viewer key
--key_owner arg Owner viewer key (deprecated)
--miner_key arg Standalone miner key
--key_mine arg Standalone miner key (deprecated)
--pass arg password for keys
--log_utxos arg (=0) Log recovered UTXOs (make sure the log
file is not exposed)
--fast_sync arg Fast sync on/off (override horizons)
--generate_recovery arg Recovery file to generate immediately
after start
--recovery_auto_path arg path and file prefix for recovery
auto-generation
--recovery_auto_period arg (=30) period (in blocks) for recovery
auto-generation

Rules configuration:
--Emission.Value0 arg (=500000000) initial coinbase emission in a single
block
--Emission.Drop0 arg (=1050000) height of the last block that still has
the initial emission, the drop is
starting from the next block
--Maturity.Coinbase arg (=240) num of blocks before coinbase UTXO can
be spent
--Maturity.Std arg (=0) num of blocks before non-coinbase UTXO
can be spent
--MaxBodySize arg (=1048576) Max block body size [bytes]
--DA.Target_s arg (=60) Desired rate of generated blocks
[seconds]
--DA.MaxAhead_s arg (=900) Block timestamp tolerance [seconds]
--DA.WindowWork arg (=120) num of blocks in the window for the
mining difficulty adjustment
--DA.WindowMedian0 arg (=25) How many blocks are considered in
calculating the timestamp median
--DA.WindowMedian1 arg (=7) Num of blocks taken at both endings of
WindowWork, to pick medians
--DA.Difficulty0 arg (=503382015) Initial difficulty
--Fork1 arg (=18446744073709551615) Height of the 1st fork
--Fork2 arg (=18446744073709551615) Height of the 2nd fork
--AllowPublicUtxos arg (=0) set to allow regular (non-coinbase) UTXO
to have non-confidential signature
--FakePoW arg (=0) Don't verify PoW. Mining is simulated by
the timer. For tests only

**Comment by ufo-project** [comment]
The exact option is  --treasury_path=treasury.bin

**Comment by davidufochain** [comment]
now it ok, thanks
