### ISSUE TITLE
ufo-node can not sync,please commit some available  peer info

### ISSUE THREAD

**Issue by cyberskycat** [ufo-project/ufochain#12]
ufo-node can not sync,please commit some available  peer info
i use this command line peer option 
`./ufo-node --peer 202.181.144.43:20015 --peer 202.181.144.44:20015 --peer 202.181.144.45:20015 --peer mainnet-node02.ufo.link:20015`
but  give `connection timed out `err info

**Comment by ufo-project** [comment]
```
mainnet-node01.ufo.link:20015
mainnet-node02.ufo.link:20015
mainnet-node03.ufo.link:20015
```
