### ISSUE TITLE
Unable to receive to address been choozen on Receive buttom

### ISSUE THREAD

**Issue by korkin25** [ufo-project/ufochain#13]
Hi, guys!:)

It may be bug...

If I sending UFO to one of addresses from "My active addresses" - the everything is ok.

But it's impossible receive coins to address choozen by "RECEIVE" buttom.

Help me please.
Thank you.

**Comment by ufo-project** [comment]
You would see an address while u click "receive" button. But the address is not in your wallet now, so you can not send UFO to this address.
You should click "copy transaction address" button or "save" button at the same page, and then this address will be stored into your wallet database, and then you can use this address as your receiving address.
