### ISSUE TITLE
Difficulty based profit calculation

### ISSUE THREAD

**Issue by korkin25** [ufo-project/ufochain#14]
Hi, great guys!

Can you say me how to calculate ufos/mh based on current difficulty of UFO?

I wish you $100 per UFO!!!:)

Thank you!

**Comment by ufo-project** [comment]
One basic UFO difficulty is 0xFFFFFF, which is the same as RVN, and 1/256 of BTC.
```
hashRate = 0xFFFFFF * current Difficulty / 60 
```

for example, at block 108533 time, difficulty is 648,370.398.
so
```
hashRate = 0xffffff * 648370.398 / 60 / 1000 / 1000 = 181297.49 MHash/s
```

**Comment by korkin25** [comment]
I wish you luck!!!
Thank you!:)
