### ISSUE TITLE
ufo-node high CPU usage

### ISSUE THREAD

**Issue by korkin25** [ufo-project/ufochain#15]
Hi, Devs!:)

Is it ok?

![image](https://user-images.githubusercontent.com/28926495/78466712-104d4100-770d-11ea-9796-ada3bee2f3b9.png)

the everything works, but the question:)

**Comment by ufo-project** [comment]
Is it OK now?

**Comment by korkin25** [comment]
No, the same. I have running two pools. They both use cpu like above. I need to use good hardware servers.
Have you changed something?  I havent seen new commit. what should change?

I running nodes like that:

--port=20001 --stratum_port=20002 --treasury_path=treasury.bin --peer mainnet-node01.ufo.link:20015,mainnet-node02.ufo.link:20015,mainnet-node03.ufo.link:20015,160.19.49.116:20015,160.19.49.122:20015,160.19.50.241:20015,160.19.50.228:20015 --stratum_use_tls=0 --mining_threads=6 --miner_key='many_hex_tralala-la' --owner_key='many_hex_tralala-la' --pass='fiat_must_die_tralalala'

:)

**Comment by ufo-project** [comment]
1. At first, check your ufo-node to see if the node is still in block syncing. The cpu usage at block syncing is really high.
2. You can try to stop wallet-api to see the cpu usage of ufo-node would recover or not.

btw, show me your hardware info.

**Comment by korkin25** [comment]
lol:) I guessed my stupid mistake:)

**Comment by ufo-project** [comment]
Oh, maybe i find it.

--mining_threads=6  means ufo-node use 6 threads of cpu to mine 
plz modify it to  --mining_threads=0

**Comment by korkin25** [comment]
Thank you! I made really stupid mistake. you right, I have removed already:)
I have making up the pool in big stress and wanted to make quicler/quicker and etc.
Thank you for your support!

**Comment by ufo-project** [comment]
It is my pleasure:)
