### ISSUE TITLE
BKEX.com is stolen my money

### ISSUE THREAD

**Issue by korkin25** [ufo-project/ufochain#17]
Dear Devs,

I need help.

bkex.com said that they havent received my coins.

I have sent them all ts details. They said no. we dont have them:)

Sender: 3c1c2ed8dee16be3fc1f55d9ac8a5545846904710835bf6db17c90950df88c401fb
Receiver: 111019d09a98f34c115c7a27f95e97f30fb38e3063adcd41057918a50b70b632d2
Amount: 50 UFO
Kernel ID: 21b5f3b5b4ee090043bbd9ef2a648be982ecb9abc058a9230a8c0f73a02caa87

UFO is anonymous coin and it allows them to stole money.

I am ready to send you my wallet.dat and seeds/password/etc.

Help me, please.

![image](https://user-images.githubusercontent.com/28926495/79110707-b3443180-7d83-11ea-8ec8-9b1009ec7a85.png)

![image](https://user-images.githubusercontent.com/28926495/79110741-c1924d80-7d83-11ea-84c2-f8a2aac928fe.png)

**Comment by ufo-project** [comment]
Sorry to hear that, but we can do nothing for helping as developers.
You'd better to communicate to BKEX and submit your deposit evidences. 
Best wishes.
