### ISSUE TITLE
Can`t send coin from remote machine

### ISSUE THREAD

**Issue by prettyCoders** [ufo-project/ufochain#20]
![图片](https://user-images.githubusercontent.com/36216120/81382273-b511d280-9140-11ea-814f-33180e3034b8.png)
![图片](https://user-images.githubusercontent.com/36216120/81382292-bcd17700-9140-11ea-9e52-3e8e2ff1aec2.png)
![图片](https://user-images.githubusercontent.com/36216120/81382308-c22ec180-9140-11ea-8727-5cedec07924a.png)

**Comment by mutalisk999** [comment]
Wallet API has the same structure as Node Stratum API protocol (`JSON RPC 2.0 over TCP connection`) and should have an online connection to the node. However, it can work `over HTTP if you will use --api_use_http=1 option`, send POST requests to http://x.x.x.x:port/api/wallet in this case.

You can check it at https://github.com/ufo-project/ufochain/wiki/UFO-wallet-protocol-API

**Comment by ufo-project** [comment]
Wallet API has the same structure as Node Stratum API protocol (`JSON RPC 2.0 over TCP connection`) and should have an online connection to the node. However, it can work `over HTTP if you will use --api_use_http=1 option`, send POST requests to http://x.x.x.x:port/api/wallet in this case.

You can check it in https://github.com/ufo-project/ufochain/wiki/UFO-wallet-protocol-API
