### ISSUE TITLE
Is there jsonrpc list of ufo node?

### ISSUE THREAD

**Issue by Airead** [ufo-project/ufochain#22]
Is there jsonrpc list of ufo node?
For example, there are json rpcs in bitcoind: getblockchaininfo, getblockcount, getblockhash, getblock.

**Comment by ufo-project** [comment]
ufo-node only has some tcp-jsonrpc apis abt mining, and please check these apis in https://github.com/ufo-project/ufochain/wiki/UFO-mining-protocol-API-(Stratum)
