### ISSUE TITLE
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found

### ISSUE THREAD

**Issue by chenym1992** [ufo-project/ufochain#3]
![image](https://user-images.githubusercontent.com/16012505/75735210-19757780-5d35-11ea-878a-5fa53c6e4a33.png)
![image](https://user-images.githubusercontent.com/16012505/75735238-298d5700-5d35-11ea-8ae1-09168478b1c8.png)

**Comment by cookedsteak** [comment]
Try to upgrade your gcc version to 9. @chenym1992

**Comment by ufo-project** [comment]
Try to upgrade gcc and libstdc++

```
sudo apt update
sudo apt install wget gcc-8 unzip libssl1.0.0 software-properties-common
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt-get install --only-upgrade libstdc++6
```

**Comment by zhangqiangup163** [comment]
I met this problem today and solved it. The above solution did not work for me. I have wrote my soltuon [here](https://github.com/UKPLab/sentence-transformers/issues/1526#issuecomment-1278627574).
