### ISSUE TITLE
wallet-api responses error

### ISSUE THREAD

**Issue by rlinxy** [ufo-project/ufochain#8]
Run the wallet-api with 

> ./wallet-api -n 127.0.0.1:1621 -p 10000 --pass 123456

then use the command as below:

> curl -d '{"jsonrpc":"2.0","id":1,"method":"wallet_status"}' -H "Content-Type: application/json" -X POST http://127.0.0.1:10000/api/wallet

Got these errors:

> I 2020-03-08.16:40:20.400 got POST /api/wallet HTTP/1.1

D 2020-03-08.16:40:20.400 onInvalidJsonRpc: {"error":{"code":-32603,"message":"[json.exception.parse_error.101] parse error at 1: syntax error - invalid literal; last read: 'P'"},"jsonrpc":"2.0"}
I 2020-03-08.16:40:20.400 got Host: 127.0.0.1:10000

D 2020-03-08.16:40:20.400 onInvalidJsonRpc: {"error":{"code":-32603,"message":"[json.exception.parse_error.101] parse error at 1: syntax error - invalid literal; last read: 'H'"},"jsonrpc":"2.0"}
I 2020-03-08.16:40:20.400 got User-Agent: curl/7.58.0

D 2020-03-08.16:40:20.400 onInvalidJsonRpc: {"error":{"code":-32603,"message":"[json.exception.parse_error.101] parse error at 1: syntax error - invalid literal; last read: 'U'"},"jsonrpc":"2.0"}
I 2020-03-08.16:40:20.400 got Accept: */*

D 2020-03-08.16:40:20.400 onInvalidJsonRpc: {"error":{"code":-32603,"message":"[json.exception.parse_error.101] parse error at 1: syntax error - invalid literal; last read: 'A'"},"jsonrpc":"2.0"}
I 2020-03-08.16:40:20.400 got Content-Type: application/json

D 2020-03-08.16:40:20.400 onInvalidJsonRpc: {"error":{"code":-32603,"message":"[json.exception.parse_error.101] parse error at 1: syntax error - invalid literal; last read: 'C'"},"jsonrpc":"2.0"}
I 2020-03-08.16:40:20.400 got Content-Length: 49

D 2020-03-08.16:40:20.400 onInvalidJsonRpc: {"error":{"code":-32603,"message":"[json.exception.parse_error.101] parse error at 1: syntax error - invalid literal; last read: 'C'"},"jsonrpc":"2.0"}
I 2020-03-08.16:40:20.400 got

D 2020-03-08.16:40:20.400 onInvalidJsonRpc: {"error":{"code":-32603,"message":"[json.exception.parse_error.101] parse error at 3: syntax error - unexpected end of input; expected '[', '{', or a literal"},"jsonrpc":"2.0"}

**Comment by rlinxy** [comment]
Did I make any mistake here? Please advise

**Comment by ufo-project** [comment]
```
./wallet-api --node_addr=127.0.0.1:1621 --pass=123456 --use_http=1 --ip_whitelist=127.0.0.1
```
